### ISSUE TITLE
Tweak Vertical Article List Element Alignment

### ISSUE THREAD

**Issue by tacc-wbomar** [TACC/Core-CMS#287]
# Status

Migrated to [FP-1249](https://jira.tacc.utexas.edu/browse/FP-1249).

> ⚠️ Retain content in this description for FP-1249 dev to reference.

# Goal

Tweak design of row-based article lists.

# Requirements

- Any row-based article list **must** have consistent distance between its items.
- The article lists in second row **must** _still_ have the same height.
- The footers of article lists in second row **must** _still_ be at the bottom of the column.

# Direction

- Snippet: [Frontera (dev)](https://dev.fronteraweb.tacc.utexas.edu/) "…287: CSS: Tweak Vertical Article List Element Alignment (last repo commit: N/A)"
- Branch: [`task/GH-287-tweak-vert-article-list-alignment`](https://github.com/TACC/Core-CMS/compare/task/GH-287-tweak-vert-article-list-alignment)

<details>
<summary>Outdated</summary>

```css
/* BEFORE */
.c-article-list--layout-e .c-article-list__item {
    flex-grow: 1;
}
/* ... */
.c-article-list__footer {
    /* ... */
}

/* AFTER */
.c-article-list--layout-e:not(.c-article-list--style-divided) .c-article-list__item {
    /* flex-grow: 0; */
    margin-top: .8rem;
}
/* ... */
.c-article-list__footer {
    /* ... */
    margin-top: auto;
}
```

__Known Issues with Code Above (Must Fix)__

The following elements do not vertically align:
- top of “Allocations” first element image
- top border of “User Guides” first element
- top border of “Training & Events” first element

</details>
